### ISSUE TITLE
Tests observed to be flaky

### ISSUE THREAD

**Issue by bittrance** [bittrance/rxruby#9]
Finding historic Travis builds can be tricky, so this case is meant to collect tests that fails randomly. Paste test name, platform and Travis link. Like so:

Travis 74 https://travis-ci.org/bittrance/rxruby/jobs/306843846#L569
```
TestCurrentThreadScheduler#test_schedule_required [/home/travis/build/bittrance/rxruby/test/rx/concurrency/test_current_thread_scheduler.rb:15]:
Expected: true
  Actual: false
```
Travis 78 https://travis-ci.org/bittrance/rxruby/jobs/306902537#L562
```
TestCurrentThreadScheduler#test_schedule_recursive_absolute_with_state_simple [/home/travis/build/bittrance/rxruby/test/rx/concurrency/helpers/immediate_local_scheduler_helper.rb:32]:
Expected: [1]
  Actual: []
```

**Comment by bittrance** [comment]
Running `while bundle exec rake ; do ; done` on jruby-9.1.8.0 produced this issue after a while:
```
TestObservableCreation#test_sampler_completes_first [/Users/quest/projects/personal/rxruby/test/rx/linq/observable/test_sample.rb:31]:
The size of messages differ.
Expected: 3
  Actual: 0
```

```
TestObservableSynchronization#test_subscribe_on [/Users/quest/projects/personal/rxruby/test/rx/operators/test_synchronization.rb:16]:
Expected: 2
  Actual: 0
```

**Comment by bittrance** [comment]
Travis 140 https://travis-ci.org/bittrance/rxruby/jobs/309697259#L561
```
TestCurrentThreadScheduler#test_schedule_error_raises [/home/travis/build/bittrance/rxruby/test/rx/concurrency/test_current_thread_scheduler.rb:31]:
StandardError expected but nothing was raised.
```

JRuby does not like `CurrentThreadScheduler` 😒

**Comment by bittrance** [comment]
Travis 245 jruby-9.1.8.0 https://travis-ci.org/bittrance/rxruby/jobs/313594855#L601

```
TestDefaultScheduler#test_schedule_relative_with_state [/home/travis/build/bittrance/rxruby/lib/rx/testing/async_testing.rb:16]:
Array expected to be 1 items but was []
```

**Comment by bittrance** [comment]
Travis 248 rbx-2.6 https://travis-ci.org/bittrance/rxruby/jobs/314471432
```
TestObservableSynchronization#test_subscribe_on_default_scheduler_with_merging [/home/travis/build/bittrance/rxruby/lib/rx/testing/async_testing.rb:16]:
Array expected to be 5 items but was [#<struct Rx::Recorded time=0, value=#<Rx::OnNextNotification:0x8e90 @value=1 @kind=:on_next>>, #<struct Rx::Recorded time=0, value=#<Rx::OnNextNotification:0x8ea0 @value=2 @kind=:on_next>>, #<struct Rx::Recorded time=0, value=#<Rx::OnNextNotification:0x8eb0 @value=3 @kind=:on_next>>, #<struct Rx::Recorded time=0, value=#<Rx::OnCompletedNotification:0x8ec0 @kind=:on_completed>>]
```

**Comment by bittrance** [comment]
Travis 248 mri-2.0 https://travis-ci.org/bittrance/rxruby/jobs/314471432
```
Rx::TestThreadedEnumerator#test_raises_stop_iteration:
fatal: No live threads left. Deadlock?
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:72:in `sleep'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:72:in `block (2 levels) in wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:68:in `block in wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:66:in `wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:196:in `block (2 levels) in pop'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:187:in `pop'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/threaded_enumerator.rb:52:in `next'
    /home/travis/build/bittrance/rxruby/test/rx/concurrency/test_threaded_enumerator.rb:20:in `block in test_raises_stop_iteration'
    /home/travis/build/bittrance/rxruby/test/rx/concurrency/test_threaded_enumerator.rb:20:in `times'
    /home/travis/build/bittrance/rxruby/test/rx/concurrency/test_threaded_enumerator.rb:20:in `test_raises_stop_iteration'
```

**Comment by bittrance** [comment]
Travis 313.
```
TestObservableSynchronization#test_subscribe_on [/Users/quest/projects/personal/rxruby/test/rx/operators/test_synchronization.rb:16]:
Expected: 2
  Actual: 0
```

**Comment by bittrance** [comment]
Travis 327 mri-2.0. https://travis-ci.org/bittrance/rxruby/jobs/322260149
```
TestObservableCreation#test_repeat_infinitely_dispose:
fatal: No live threads left. Deadlock?
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:72:in `sleep'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:72:in `block (2 levels) in wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:68:in `block in wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:66:in `wait'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:196:in `block (2 levels) in pop'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
    /home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb:187:in `pop'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/threaded_enumerator.rb:52:in `next'
    /home/travis/build/bittrance/rxruby/lib/rx/operators/multiple.rb:570:in `block (3 levels) in concat'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/async_lock.rb:40:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/async_lock.rb:40:in `block in wait'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/async_lock.rb:27:in `loop'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/async_lock.rb:27:in `wait'
    /home/travis/build/bittrance/rxruby/lib/rx/operators/multiple.rb:561:in `block (2 levels) in concat'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:36:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:36:in `block in schedule_recursive'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:96:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:96:in `block in invoke_recursive'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:109:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:109:in `block (3 levels) in invoke_recursive'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduled_item.rb:29:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduled_item.rb:29:in `invoke'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/current_thread_scheduler.rb:57:in `run_trampoline'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/current_thread_scheduler.rb:38:in `schedule_relative_with_state'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/local_scheduler.rb:20:in `schedule_with_state'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:100:in `block (2 levels) in invoke_recursive'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:36:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduler.rb:36:in `block (2 levels) in schedule_recursive'
    /home/travis/build/bittrance/rxruby/lib/rx/operators/multiple.rb:595:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/operators/multiple.rb:595:in `block (5 levels) in concat'
    /home/travis/build/bittrance/rxruby/lib/rx/core/observer.rb:106:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/core/observer.rb:106:in `on_completed'
    /home/travis/build/bittrance/rxruby/lib/rx/core/auto_detach_observer.rb:30:in `on_completed_core'
    /home/travis/build/bittrance/rxruby/lib/rx/core/observer.rb:106:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/core/observer.rb:106:in `on_completed'
    /home/travis/build/bittrance/rxruby/lib/rx/operators/creation.rb:103:in `block (2 levels) in just'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/virtual_time_scheduler.rb:164:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/virtual_time_scheduler.rb:164:in `invoke'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/virtual_time_scheduler.rb:89:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/virtual_time_scheduler.rb:89:in `block in schedule_at_absolute_with_state'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduled_item.rb:29:in `call'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/scheduled_item.rb:29:in `invoke'
    /home/travis/build/bittrance/rxruby/lib/rx/concurrency/virtual_time_scheduler.rb:40:in `start'
    /home/travis/build/bittrance/rxruby/lib/rx/testing/test_scheduler.rb:76:in `configure'
    /home/travis/build/bittrance/rxruby/test/rx/core/test_observable_creation.rb:498:in `test_repeat_infinitely_dispose'
```
